### ISSUE TITLE
angular Sweet Alert

### ISSUE THREAD

**Issue by vaishali456** [leftstick/angular-sweetalert#11]
I used to use this url https://leftstick.github.io/angular-sweetalert/bower/sweetalert/dist/sweetalert.css but it says 404 not found ?? why  is that so ?? I am using this for one of my client please help me asap

**Comment by leftstick** [comment]
`sweetalert` was pushed by accident, it should be maintained by [sweetalert](https://github.com/t4t5/sweetalert/) itself, not me.

I was not expecting anyone referring it from my repo, that's why i removed it yesterday(Just found i pushed them yesterday^^). 

You can referring it from [sweetalert.css](https://github.com/t4t5/sweetalert/blob/master/dist/sweetalert.css) directory
